#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
make_preview.py -- build a readable PDF of the manuscript WITHOUT REVTeX.

WHY THIS EXISTS

`paper4_manuscript.tex` is written for REVTeX 4.2, the class Physical Review
requires. If REVTeX is not installed, the build fails at the first line with

    ! LaTeX Error: File `revtex4-2.cls' not found.

and no PDF is produced. Installing REVTeX is the right fix (see
README_paper.md); this script is for reading the manuscript in the meantime,
and for anyone who wants to review the text without an APS-capable TeX
installation.

WHAT IT PRODUCES, AND WHAT IT IS NOT

A SINGLE-COLUMN preprint-style PDF. That is a deliberate difference from the
journal layout, not an oversight. In two columns each figure has to be hoisted
to the top of a column, and with five figures and three tables competing for
those slots LaTeX defers most of them to the end of the document -- which
makes a reading copy useless precisely where the figures matter. In one column
a float can sit in the text that discusses it.

Consequently this PDF must not be used to judge anything about the journal
version: column widths, the title block, table rules, abstract format, float
placement and page count all differ. Figures are also scaled here to the text
width, whereas the manuscript uses them at their native 8.6/17.2 cm.

The one thing it does show faithfully is the text, and the order in which
figures and tables are discussed.

Usage
-----
    python make_preview.py                 # writes paper4_manuscript_PREVIEW.pdf
    python make_preview.py --keep-tex      # also leave preview.tex for inspection
"""

from __future__ import annotations

import argparse
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(HERE, "paper4_manuscript.tex")
OUT = "paper4_manuscript_PREVIEW"

PREAMBLE = (
    r"\documentclass[11pt]{article}"
    r"\usepackage[margin=2.4cm]{geometry}"
    r"\usepackage{graphicx}\usepackage{amsmath}\usepackage{amssymb}\usepackage{url}"
    r"\usepackage[font=small]{caption}"
    # REVTeX-only commands that article does not define
    r"\newcommand{\affiliation}[1]{}\newcommand{\email}[1]{}"
    r"\newenvironment{ruledtabular}{}{}"
    # in one column the starred (double-width) floats are ordinary floats
    r"\renewenvironment{figure*}[1][]{\begin{figure}[!ht]}{\end{figure}}"
    r"\renewenvironment{table*}[1][]{\begin{table}[!ht]}{\end{table}}"
    # let floats stay near their text instead of being deferred to the end
    r"\renewcommand{\topfraction}{0.9}\renewcommand{\bottomfraction}{0.7}"
    r"\renewcommand{\textfraction}{0.1}\renewcommand{\floatpagefraction}{0.75}"
    r"\setcounter{topnumber}{3}\setcounter{totalnumber}{5}"
)

# Figures 1-3 are tall two-panel single-column figures; at full text width they
# would run off the page, so they are given a fraction of it.
TALL = ("fig_1", "fig_2", "fig_3")


def transform(tex: str) -> str:
    s = tex.replace(
        "\\documentclass[aps,pre,twocolumn,superscriptaddress,floatfix,"
        "longbibliography]{revtex4-2}", PREAMBLE)
    # packages already pulled in by the preamble above
    s = s.replace("\\usepackage{graphicx}\n\\usepackage{amsmath}\n"
                  "\\usepackage{amssymb}\n\\usepackage{url}\n", "")

    # REVTeX prints the abstract after the title block even though the source
    # places it before \maketitle; article prints it where it stands.
    m = re.search(r"\\begin\{abstract\}.*?\\end\{abstract\}\s*", s, re.S)
    if m:
        s = s.replace(m.group(0), "").replace("\\maketitle",
                                              "\\maketitle\n" + m.group(0))

    # article has no \email or \affiliation, so build the byline by hand
    s = s.replace(
        "\\author{Ruqing Chen}",
        "\\author{Ruqing Chen \\\\ \\texttt{ruqing@hotmail.com} \\\\ "
        "\\textit{GUT Geoservice Inc., Montr\\'eal, Qu\\'ebec, Canada}}")

    s = re.sub(r"\\includegraphics\{(fig_[a-z0-9_]+)\}",
               lambda m2: "\\includegraphics[width=%s\\linewidth]{%s}"
                          % ("0.62" if m2.group(1) in TALL else "1.0",
                             m2.group(1)), s)
    s = s.replace("\\begin{figure}[t]", "\\begin{figure}[!ht]\n\\centering")
    s = s.replace("\\begin{table}[t]", "\\begin{table}[!ht]\n\\centering")
    return ("% PREVIEW BUILD -- single column, substitute document class.\n"
            "% NOT the REVTeX layout. Generated by make_preview.py.\n") + s


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--keep-tex", action="store_true")
    args = ap.parse_args()

    if shutil.which("pdflatex") is None:
        sys.exit("pdflatex not found on PATH.")
    if not os.path.exists(SRC):
        sys.exit(f"{SRC} not found; run this from the paper/ directory.")

    tmp = os.path.join(HERE, "preview.tex")
    with open(tmp, "w") as fh:
        fh.write(transform(open(SRC).read()))

    for _ in range(2):          # second pass resolves cross-references
        r = subprocess.run(["pdflatex", "-interaction=nonstopmode", "preview.tex"],
                           cwd=HERE, capture_output=True, text=True)
    log = os.path.join(HERE, "preview.log")
    errors = [l for l in open(log, errors="ignore") if l.startswith("!")] \
        if os.path.exists(log) else []
    if not os.path.exists(os.path.join(HERE, "preview.pdf")):
        sys.exit("build failed:\n" + "".join(errors[:10]) or r.stdout[-2000:])

    os.replace(os.path.join(HERE, "preview.pdf"),
               os.path.join(HERE, OUT + ".pdf"))
    for ext in (".aux", ".log", ".out"):
        p = os.path.join(HERE, "preview" + ext)
        if os.path.exists(p):
            os.remove(p)
    if not args.keep_tex:
        os.remove(tmp)

    print(f"wrote {OUT}.pdf" + (f"  ({len(errors)} LaTeX errors)" if errors
                                else "  (no LaTeX errors)"))
    print("This is a reading copy, not the journal layout. See README_paper.md.")


if __name__ == "__main__":
    main()
